spring:
  datasource:
    url: jdbc:mysql:///openapi-admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1111
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
