spring:
  datasource:
    url: jdbc:mysql:///public_params?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1111
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
